version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: on-failure:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure:10
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 15432:80